/* TESHIS DUZELTME SOZLUGU (sokum turu, 4 Eyl 2026) — kaynak L.tr.f 11101-
   11128 ve L.en.f 11197-11224 BIREBIR; sira PRIO 11257-11259. kabuk-derle
   public/varlik/tespit-fix.<dil>.json yazar ([anahtar, baslik, aciklama]);
   STETespit adasi gonderimde indirir. Son kayit 'yok': kritik eksik yok. */
export const PRIO = ['https', 'viewport', 'contact', 'whatsapp', 'schema', 'desc', 'title', 'analytics',
  'inline', 'blocking', 'compress', 'weight', 'imgdim', 'imgfmt', 'cache', 'fonts', 'reqs',
  'og', 'local', 'h1', 'alt', 'sitemap', 'canonical', 'robots'];
export const FIX = {
  tr: {
    schema: ['Yapay zekâ seni okuyamıyor', 'Sitede yapılandırılmış veri yok. Yeni arama yanıtları bunu okur — olmayınca markan o cevaplarda hiç geçmez.'],
    desc: ['Arama sonucunda cümlen yok', 'Açıklama etiketi eksik. Google rastgele bir cümle gösteriyor.'],
    title: ['Sekme başlığı satmıyor', 'Başlık yok ya da arama sonucunda kesiliyor.'],
    contact: ['Ulaşmak zor', 'Ziyaretçi sana ulaşmak için uğraşıyor. En az iki yol olmalı.'],
    whatsapp: ['WhatsApp yok', 'Türkiye’de talebin çoğu WhatsApp’tan gelir.'],
    analytics: ['Ölçüm yok', 'Hangi kanaldan kaç kişi geliyor bilinmiyor.'],
    weight: ['Sayfa fazla ağır', 'Görseller sıkıştırılmamış.'],
    inline: ['Sayfanın büyük kısmı gömülü kod', 'Bu kod önbelleğe alınamıyor — ikinci sayfaya geçen ziyaretçi aynı yükü tekrar indiriyor.'],
    blocking: ['Açılış kapıda bekliyor', 'Head içindeki stil ve betikler ilk boyamayı geciktiriyor.'],
    fonts: ['Yazı tipi yükü fazla', 'Her aile ve varyant ayrı bir istek; dışarıdan gelenler ayrıca dış bağımlılık.'],
    imgdim: ['Görsellerin boyutu yazılmamış', 'Sayfa yüklenirken içerik zıplıyor, ziyaretçi yanlış yere tıklıyor.'],
    imgfmt: ['Görseller eski formatta', 'WebP/AVIF aynı görseli belirgin daha küçük indirir.'],
    compress: ['Sıkıştırma kapalı', 'Sunucu metni sıkıştırmadan gönderiyor — en ucuz kazanç burada.'],
    cache: ['Belge önbelleğe alınmıyor', 'Bu sayfanın kendi başlığı saklanmasını engelliyor; her ziyaret sıfırdan iniyor.'],
    reqs: ['Çok fazla dış kaynak', 'Her referans ayrı bir istek; sayfa parça parça açılıyor.'],
    viewport: ['Mobil ayarı yok', 'Ziyaretçinin çoğu telefondan geliyor.'],
    og: ['Paylaşınca kart boş', 'Link görselsiz görünüyor — güven kaybı.'],
    local: ['Yerel kayıt görünmüyor', '"Yakınımda" aramalarında çıkmazsın.'],
    h1: ['Ana başlık düzensiz', 'Sayfada tek ve net bir H1 olmalı.'],
    alt: ['Görseller tanımsız', 'Görsel aramada çıkmıyorsun.'],
    https: ['Güvenli bağlantı yok', 'Tarayıcı ziyaretçiye uyarı gösteriyor.'],
    sitemap: ['Site haritası yok', 'Arama motoru sayfaları tek tek keşfediyor.'],
    robots: ['robots.txt yok', 'Tarayıcılara yön veremiyorsun.'],
    canonical: ['Adres tekrarı riski', 'Aynı sayfa farklı adreslerle açılıyor.'],
    yok: ['Kritik bir eksik çıkmadı.', 'Temel yerinde. Bundan sonraki kazanç tamirde değil, stratejide.'],
  },
  en: {
    schema: ['AI cannot read you', 'No structured data — your brand never appears in AI answers.'],
    desc: ['No sentence in search results', 'The description tag is missing or weak.'],
    title: ['The page title is not selling', 'Missing or truncated in search results.'],
    contact: ['Hard to reach you', 'Visitors have to work to contact you.'],
    whatsapp: ['No WhatsApp', 'Most enquiries arrive on WhatsApp.'],
    analytics: ['No measurement', 'You cannot see which channel brings whom.'],
    weight: ['Page is too heavy', 'Images are not compressed.'],
    inline: ['Most of the page is inline code', 'This code cannot be cached — a visitor moving to a second page downloads the same weight again.'],
    blocking: ['The first paint is held at the door', 'Stylesheets and scripts in the head delay it.'],
    fonts: ['Too much font weight', 'Every family and variant is a separate request; external ones add a dependency.'],
    imgdim: ['Images have no dimensions', 'Content jumps while the page loads and visitors tap the wrong thing.'],
    imgfmt: ['Images use legacy formats', 'WebP/AVIF deliver the same image noticeably smaller.'],
    compress: ['Compression is off', 'The server sends text uncompressed — the cheapest win is here.'],
    cache: ['The document is not cacheable', 'This page’s own header blocks storage; every visit downloads it from scratch.'],
    reqs: ['Too many external resources', 'Each reference is a separate request; the page arrives in pieces.'],
    viewport: ['No mobile setup', 'Most visitors are on phones.'],
    og: ['Empty share card', 'Your link shows no image.'],
    local: ['No local footprint', 'You miss "near me" searches.'],
    h1: ['Heading structure is off', 'There should be exactly one clear H1.'],
    alt: ['Images are undefined', 'You miss image search.'],
    https: ['No secure connection', 'Browsers warn your visitors.'],
    sitemap: ['No sitemap', 'Crawlers must discover pages one by one.'],
    robots: ['No robots.txt', 'You cannot guide crawlers.'],
    canonical: ['Duplicate URL risk', 'The same page opens on several URLs.'],
    yok: ['Nothing critical found.', 'The basics are in place.'],
  },
};
